### ISSUE TITLE
미들웨어 구현 방식에 대한 의견

### ISSUE THREAD

**Issue by kyungmi** [ridi/php-oauth2#4]
**실제로 뷰어 API 서버인 php-web과 WebViewer에 적용해 봤는데, 아래와 같이 몇 가지 문제가 발견되어 적용에 어려움이 있었습니다.**

예상과 다르게 실제 사용 흐름이 다음과 같았고, 현재의 구조로는 각 단계를 진행할 때 문제가 있다는 것을 파악했습니다.

#### 기대 사용 흐름
| 단계 | 로그인이 필요하지 않음 | 로그인이 필요 |
| ------------- | ------------- | ------------- |
| 1. 토큰 파싱 `introspect()` | 오류 발생시 400 에러 | 오류 발생시 400 에러 |
| 2. 토큰 유효성 체크 `loginRequired()` | (skip) | 오류 발생시 401 에러 |
| 3. scope 체크 | (skip) | 오류 발생시 403 에러 |

#### 실제 사용 흐름

| 단계 | 로그인이 필요하지 않음 | 로그인이 필요 |
| ------------- | ------------- | ------------- |
| 1. `access_token` 유무 체크 | 오류 무시 | 없을 경우 (API의 경우)401 에러, (페이지인 경우)/authorize로 이동 |
| 2. `access_token` 파싱(= `introspect()`) <br>+ 유효성 체크(= `loginRequired()`) **<sup>[1]</sup>** | 오류 무시(혹은 400/401 에러) **<sup>[2]</sup>**  |  오류 발생시 (API의 경우)401 에러, (페이지인 경우)/authorize로 이동 |
| 3. scope 체크 | (skip) | scope 누락시 (API의 경우)403 에러, (페이지인 경우) /authorize(+ scope)로 이동(?) |
| 4. `access_token`을 각 애플리케이션의 user 객체로 변환 **<sup>[3]</sup>** | 오류 무시 | 오류 발생시 (API의 경우)401 에러, (페이지인 경우)/authorize로 이동 |

**<sup>[1]</sup>** 원래는 토큰의 유효기간 체크를 `loginRequired()` 단계에서 체크하도록 했었는데, JWT 토큰 유효기간이 지났을 경우에 토큰을 파싱해 사용자 정보를 추출하는 것이 아무 의미가 없었습니다. 이전처럼 유효기간 체크까지 해주는 `firebase/php-jwt`를 사용하는 것으로 다시 바꾸는게 좋을 것 같습니다.

**<sup>[2]</sup>** 미들웨어 특성상 익셉션이 발생하게 되면 거기서 다음 미들웨어로 더 이상 진행되지 않고 오류를 뱉게 되기 때문에 토큰 파싱 관련 오류를 무시하고 사용자에게 알리지 않는 것이 불가능합니다. 
물론 그렇다고 오류를 무시하게끔 변경하면 파싱 관련 오류 핸들링을 어디에서도 할 수 없게 되는 문제가 있습니다.
현재 구현(아래)에서는 `ExpiredTokenException`나 `InvalidTokenException`이 발생할 수 있어서 이 때 발생하는 오류를 무시하기 위해 `try~catch`블록을 사용하고 있습니다. 원래는 400 오류를 발생시키려고 했었는데, 이게 맞는지 의문이 들더라고요. 그래서 결국 무시하는 쪽으로 코드를 변경했습니다.

**<sup>[3]</sup>** 이 부분을 위해 각 애플리케이션에서 1) 미들웨어를 하나 더 추가해서 처리하는 방법도 있고, 2)제공하는 미들웨어의 파라미터로 콜백 함수를 받아 처리하는 방법도 있을 것 같습니다. 1)의 경우 라이브러리 사용자가 직접 파싱된 토큰 정보를 저장하는 attribute(`ACCESS_TOKEN_INFO_KEY`)에 직접 접근해 값을 가져와야 합니다.

---

위와 같은 여러 가지 제약때문에 결국 처음에 준형님이 제안해주신 PR 방향과 비슷하게 미들웨어를 재구성해서 사용하게 되었습니다. (임시, scope 체크는 제외됨)

로그인이 필요하지 않은 경우 `getUserInfo(false)`를, 로그인이 필요한 경우 `getUserInfo(true)`를 호출합니다.

```php
// 미들웨어 
   private static function checkOAuth2(Request $request)
    {
        if (!self::$jwt_info) {
            self::$jwt_info = new JwtInfo(\Config::$OAUTH2_JWT_SECRET, new HS256());
        }
        OAuth2MiddlewareFactory::introspect(self::$jwt_info)($request);
        OAuth2MiddlewareFactory::loginRequired()($request); // [1] 문제로 인해 expired 여부를 공통으로 체크
        $token = $request->attributes->get(AccessTokenConstant::ACCESS_TOKEN_INFO_KEY);
        try {
            $user = new User($token->getSubject());
            $request->attributes->set(self::USER_INFO_KEY, $user);
        } catch (RidiErrorException $e) {
            throw new HttpException(Response::HTTP_UNAUTHORIZED);
        }
    }

    public static function getUserInfo($login_required = false)
    {
        if (\Config::$ENABLE_OAUTH2) {
            return function(Request $request) use ($login_required) {
                try {
                    self::checkOAuth2($request);
                } catch (HttpException $e) {
                    if ($login_required) {
                        $error_code = ErrorCode::getDefaultByStatusCode($e->getStatusCode(), $e->getMessage());
                        throw new ViewerApiException($error_code);
                    }
                }
            };
        } else {
            ...
        }
    }

```

---

**아무래도 미들웨어 함수를**

1) **단계별이 아니라 실제 사용 흐름에 맞추어 로그인이 필요한 경우 / 필요하지 않은 경우로 나누어 구현하고 각 상황에 맞는 callback 함수들<sup>[2][3]참고</sup>을 넘겨서 처리하게 하거나**
2) **아예 미들웨어를 제공하지 않고 직접 조합해서 쓰거나,**
3) **[Passport](http://www.passportjs.org/docs/oauth/#configuration)처럼 다양한 설정 값(`clinet_id`, `client_secret`, `JWTInfo`, OAuth2 endpoint(/authorize 정도?), `userConverter`<sup>[3]참고</sup>, errorHandler<sup>[2]참고</sup> 등)들을 넘길 수 있는 [Provider](https://silex.symfony.com/doc/1.3/providers.html) 방식으로 구현을 바꾸는 것**

**등의 방법이 있을 것 같은데, 어떻게 생각하시나요?**

**Comment by kyungmi** [comment]
@namenu @antiline @imkitae 
답변 부탁드립니다~

**Comment by kyungmi** [comment]
그리고 현재 introspect를 로컬에서 진행하게끔 되어 있는데, revoke등을 판단하기 위해서라도 account 서버 대상으로 introspect를 해보는 것이 좋을 것 같습니다. 이 부분은 token refresher가 잘 해줄 것이라고 믿고 위임하면 되는건가요?

**Comment by antiline** [comment]
JWT 라 revoke 는 없습니다. 판단을 각 로컬에서 하기로 했기 때문에 내부 서비스 대상 introspect 은 account 서버에서 제공하지 않습니다.
token refresher도 검증이 아니라 갱신만 합니다.
token refresher가 적절히 갱신 해준다고 믿으시면 될것 같습니다.

**Comment by antiline** [comment]
3번이 좋은것 같습니다.

**Comment by namenu** [comment]
미들웨어를 사용하지 않는다고 하여 반드시 Provider를 제공할 필요는 없을 것 같습니다.
(게다가 Silex는 이제 개발이 중단되고 Symfony 4로 통합이 되어서...)

저는 2번과 예제를 제공하는게 나을 수도 있다는 생각이 드네요.

**Comment by kyungmi** [comment]
@namenu 헉. Silex 개발이 중단되었군요... 
미들웨어를 쓰지 않게 되서 그 대신 Provider를 쓰겠다는 뜻은 아니었고요. Middleware만 가지고 해당 기능을 개발하는데 제약사항(함수에 자잘한 설정을 넘기거나 콜백을 넘겨야 하는 등의)이 많아서 Provider를 고려해봤습니다. 
현재 미들웨어 상태로는 어디에서도 그대로 사용하기는 힘들 것 같습니다.

일단 제가 미들웨어 없이 예제를 작성해보고 기능이 너무 크다 싶으면 Provider나 이와 대응되는 Symfony의 기능(찾아봐야겠네요.)을 활용해 제공하는 것으로 해보겠습니다.

위의 **실제 사용 흐름**에는 다들 동의하시나요?

**Comment by imkitae** [comment]
저도 2번 + 예제를 제공하는 방식에 찬성합니다.  
사용흐름 시나리오도 php-oauth2를 사용하는 서비스마다 다를 수 있을 것 같아요.  
실제 사용을 예측해서 미들웨어를 제공하기 쉽지 않기 때문에 직접 구현해서 사용하도록 하는 것이 유연할 것 같습니다.

**Comment by namenu** [comment]
@kyungmi 

구체적인 예시 혹은 코드를 보면 좀 와닿을 것 같습니다.

1. '로그인이 필요하지 않음'에도 미들웨어가 설치되는 API는 어떤 것인가요?
  - #2 에서도 잠깐 논의되었지만, 로그인 유무에 따라 결과가 달라지는 API는 본질적으로 복잡하므로 이런 상황을 최대한 피했으면 해서요. 실제 뷰어팀에서 어떤 사례가 있는지 궁금합니다.

2. '실제 사용 흐름 > (페이지인 경우)' 라고 되어있는 것은 어떤 상황인가요?
  - 어떤 API의 에러코드가 요청 문맥에 따라 401 혹은 302 여부가 정해지는 것이 어색하게 느껴집니다.

**Comment by namenu** [comment]
@kyungmi 

상세한 예시 감사합니다.

말씀하신 부분에 동의하고, '로그인 하지 않더라도...' 라는 수식어가 붙는 순간 미들웨어가 아닌 Provider 형태의 라이브러리를 사용하는 것이 좋겠습니다. (그러면 굳이 미들웨어를 제공할 필요가 있을까, 라는 생각이 드네요)

또한 리디렉션을 처리하는 주체가 리소스서버라고 생각했는데, 클라이언트이기 때문에 문제가 되지 않겠네요.

두 가지 궁금증 모두 해결이 되었습니다. 😄
